server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /console/ {
        proxy_pass http://console:4173/console/;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }

    location /api/ {
        proxy_pass http://console:4173/api/;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }
}
